// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1h04hUQa7PQpruU1ot7T3n5k4w6kDCw',
    appId: '1:735499765112:web:09aed57e05651a7f0a748d',
    messagingSenderId: '735499765112',
    projectId: 'taxiride-c8409',
    authDomain: 'taxiride-c8409.firebaseapp.com',
    storageBucket: 'taxiride-c8409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2gGrUqHDlmS1pYwoVdoeMnr0Rg4kzsg',
    appId: '1:735499765112:android:65329ac1f194359e0a748d',
    messagingSenderId: '735499765112',
    projectId: 'taxiride-c8409',
    storageBucket: 'taxiride-c8409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWmGFXZd6dW2gt43qHe9wnbjW0Guzkvs',
    appId: '1:735499765112:ios:8b39c7bc63f918970a748d',
    messagingSenderId: '735499765112',
    projectId: 'taxiride-c8409',
    storageBucket: 'taxiride-c8409.appspot.com',
    iosBundleId: 'com.example.taxiRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiWmGFXZd6dW2gt43qHe9wnbjW0Guzkvs',
    appId: '1:735499765112:ios:8b39c7bc63f918970a748d',
    messagingSenderId: '735499765112',
    projectId: 'taxiride-c8409',
    storageBucket: 'taxiride-c8409.appspot.com',
    iosBundleId: 'com.example.taxiRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi1h04hUQa7PQpruU1ot7T3n5k4w6kDCw',
    appId: '1:735499765112:web:eec10d77c72613d60a748d',
    messagingSenderId: '735499765112',
    projectId: 'taxiride-c8409',
    authDomain: 'taxiride-c8409.firebaseapp.com',
    storageBucket: 'taxiride-c8409.appspot.com',
  );
}
